name: Dev Version and Release

on:
  push:

  # exclude push for these files / dir
    paths:
      - '**.js'
      - '!**.config.js'
      - '!.github/**'
      - '!Competitors/**'
      - '!docs/**'
      - '!readme/**'

env:
  node_version: lts/*
  new_version: patch
  
concurrency: # prevent concurrent releases
  group: npm-bump
  cancel-in-progress: true

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    outputs:
      tagName: ${{ steps.npm-bump.outputs.release_tag }}
    steps:
    - uses: actions/checkout@v3
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}
        # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
        registry-url: 'https://registry.npmjs.org'
    - run: npm i
    - run: npm test

    # https://github.com/marketplace/actions/npm-bump
    - name: Version and publish to npm
      id: npm-bump
      uses: bcomnes/npm-bump@v2
      with:
        git_email: stephan@learnsense.org
        git_username: ${{ github.actor }}
        newversion: ${{ env.new_version }}
        publish_cmd: npm publish --tag dev
        push_version_commit: true # if your prePublishOnly step pushes git commits, you can omit this input or set it to false.
        github_token: ${{ secrets.GITHUB_TOKEN }} # built in actions token.  Passed tp gh-release if in use.
        npm_token: ${{ secrets.NPM_TOKEN }} # user set secret token generated at npm
    - run: echo ${{ steps.npm-bump.outputs.release_tag }}

    # Trigger tests on BrowserStackSelenium repo
    - name: Test
      
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -u "StephanLuis:${{secrets.PAT_KEY}}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/StephanLuis/BrowserStackSelenium/actions/workflows/79764882/dispatches \
        -d '{"ref":"main"}'
